# constants
author_name: Arthur Malumian

# plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# permalink
permalink: /:title/

# excerpt
excerpt_separator: <!--more-->

# paginate
paginate: 10;
paginate_path: '/page/:num/'

# sitemap
defaults:
  - scope:
      path: 'pdf'
    values:
      sitemap: false

# syntax
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# SEO
url: https://www.malumian.dev
author: Arthur Malumian
twitter:
  username: amalumian
logo: /assets/images/wide-logo.png
webmaster_verifications:
  google: 6BZTRqcdqKLNwlSNQxc8qqbARBH8_K2UGhtc0GlQafA
  yandex: db8c87467f0d3380

#exclude
exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile
