version: '3'
services:
  jekyll:
    build: .
    image: www.amalumian.dev
    container_name: www.amalumian.dev_container
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    environment:
      - JEKYLL_ENV=development
    command:
      ['bundle', 'exec', 'jekyll', 'serve', '--livereload', '--host', '0.0.0.0']
